# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wptags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='occurrences',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
    ]
