# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 16:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='saved',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 21, 16, 2, 16, 556871, tzinfo=utc)),
        ),
    ]
