# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_auto_20160421_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='saved',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
