# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-25 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_auto_20160422_1156'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set([('user', 'url')]),
        ),
    ]
